app_code/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from flask_login import UserMixin
from app_code import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)
    email = db.Column(db.String(30), nullable=False)
    password_hash = db.Column(db.String(128))
    budget = db.Column(db.Integer, nullable=False, default=1000)
    member_since = db.Column(db.DateTime, default=datetime.utcnow)

    user_items = db.relationship('Item', backref='owner', lazy=True)

    def __init__(self, name, email, password):
        self.name = name
        self.email = email
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Item(db.Model):

    __tablename__ = 'items'

    id = db.Column(db.Integer, primary_key=True)
    owner_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    name = db.Column(db.String(30), nullable=False)
    barcode = db.Column(db.String(12), unique=True)
    price = db.Column(db.Integer, nullable=False)
    description = db.Column(db.String(500), nullable=False)

    def __init__(self, name, barcode, price, description, owner_id):
        self.name = name
        self.barcode = barcode
        self.price = price
        self.description = description
        self.owner_id = owner_id


# db.create_all()

app_code/forms.py
from flask.app import Flask
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TextAreaField, SubmitField, ValidationError, IntegerField
from wtforms.validators import Email, EqualTo, DataRequired, Length
from .models import User, Item


class SignUpForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo(
        'password_conf', message='Passwords should match')])
    password_conf = PasswordField(
        'Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register')

    def validate_email(self, email):

        if User.query.filter_by(email=self.email.data).first():
            raise ValidationError('Email has been already registered')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

    def validate_email(self, email):

        if not User.query.filter_by(email=self.email.data).first():
            raise ValidationError('Invalid email!')


class ItemForm(FlaskForm):

    name = StringField('Name', validators=[DataRequired()])
    barcode = StringField('Barcode', validators=[DataRequired(),
                                                 Length(min=12, max=12, message='Twelve characters required')])
    price = IntegerField('Price', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    submit = SubmitField('Add')

    def validate_barcode(self, barcode):

        if Item.query.filter_by(barcode=self.barcode.data).first():
            raise ValidationError('Barcode already exists!')

app_code/__init__.py
from flask import Flask
from flask_bs4 import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)
Bootstrap(app)

app.config['SECRET_KEY'] = 'e2353ddeb887430fa070a2ace07dd719'
app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite:///database.db"
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app, db)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'auth.login'

from .auth import auth
from .views import views

app.register_blueprint(views, url_prefix='/')
app.register_blueprint(auth, url_prefix='/')

app_code/auth.py
from flask import render_template, Blueprint, redirect, url_for, flash
from flask_login import login_user, current_user, logout_user, login_required
from .forms import LoginForm, SignUpForm
from .models import User
from app_code import db

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Login Success!")
            return redirect(url_for('views.home'))
        else:
            flash("The password you entered is wrong!")
            return redirect(url_for('auth.login'))

    return render_template('login.html', form=form)


@auth.route('/logout')
@login_required
def logout():

    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/signup', methods=['GET', 'POST'])
def signup():

    form = SignUpForm()

    if form.validate_on_submit():
        user = User(name=form.name.data,
                    email=form.email.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Signup Successful!")
        return redirect(url_for('auth.login'))

    return render_template('signup.html', form=form)

app_code/views.py
from flask import render_template, Blueprint, redirect, url_for
from flask_login import current_user, login_required
from app_code import db

from .forms import ItemForm
from .models import Item, User

views = Blueprint('views', __name__)


@views.route('/')
def home():
    return render_template('home.html')


@views.route('/market')
def market_page():
    # items = [
    #     {'id': 1, 'name': 'Phone', 'barcode': '893212299897', 'price': 500},
    #     {'id': 2, 'name': 'Laptop', 'barcode': '123985473165', 'price': 900},
    #     {'id': 3, 'name': 'Keyboard', 'barcode': '231985128446', 'price': 150}
    # ]
    items = Item.query.all()
    return render_template('market.html', items=items)


@views.route('/add_item', methods=['GET', 'POST'])
@login_required
def add_item():

    form = ItemForm()

    if form.validate_on_submit():
        item = Item(name=form.name.data,
                    barcode=form.barcode.data,
                    price=form.price.data,
                    description=form.description.data,
                    owner_id=current_user.id)
        db.session.add(item)
        db.session.commit()

        return redirect(url_for('views.user_items'))
    return render_template('add_item.html', form=form)


@views.route('user_items')
@login_required
def user_items():
    items = Item.query.filter_by(owner=current_user).all()
    return render_template('user_items.html', items=items)

app_code/templates/add_item.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Add Item{% endblock %}

{% block con %}
<br>
<h2>Add Item</h2><br>
{{ wtf.quick_form(form) }}
{% endblock %}

app_code/templates/base.html
{% extends "bootstrap/base.html" %}

{% block head %}
{{ super() }}
{% block styles %}
{{ super() }}

{% endblock %}
{% endblock %}

{% block title %}Home{% endblock %}


{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('views.home') }}">Flask Market</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.home') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.market_page') }}">Market</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.add_item') }}">Add Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.user_items') }}">My Items</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">Signup</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}


{% block content %}
{% block f %}
{% for message in get_flashed_messages() %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endblock %}
<div class="container">
    {% block con %}

    {% endblock %}
</div>
{% endblock %}

app_code/templates/home.html
{% extends 'base.html' %}

{% block con %}
    <br>
    {% if current_user.is_authenticated %}
        <h2>Hello {{ current_user.name }}</h2>
    {% else %}
    <h2>Hello</h2>
    {% endif %}
{% endblock %}

app_code/templates/login.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Login{% endblock %}

{% block con %}
<br>
<h2>Login</h2><br>
{{ wtf.quick_form(form) }}
{% endblock %}

app_code/templates/market.html
{% extends 'base.html' %}

{% block title %}Flask Market{% endblock %}

{% block con %}
<br>
<h2>Market</h2><br>
<table class="table table-striped table-hover table-bordered ">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Barcode</th>
      <th scope="col">Price</th>
      <th scope="col">Owner</th>
      <th scope="col">Options</th>
    </tr>
  </thead>
  <tbody>
    {% for item in items %}
    <tr>
      <th scope="row">{{ item.id }}</th>
      <td>{{ item.name }}</td>
      <td>{{ item.barcode }}</td>
      <td>₹{{ item.price }}</td>
      <td>{{ item.owner.name }}</td>
      <td>
        <button class="btn btn-outline btn-info">More Info</button>
        <button class="btn btn-outline btn-success">Buy</button>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

app_code/templates/signup.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Signup{% endblock %}

{% block con %}
<br>
<h2>Signup</h2><br>
{{ wtf.quick_form(form) }}
{% endblock %}

app_code/templates/user_items.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}My Items{% endblock %}

{% block con %}
<br>
<h2>My Items</h2><br>
<table class="table table-striped table-hover table-bordered ">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Barcode</th>
            <th scope="col">Price</th>
            <th scope="col">Description</th>
        </tr>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <th scope="row">{{ item.id }}</th>
            <td>{{ item.name }}</td>
            <td>{{ item.barcode }}</td>
            <td>₹{{ item.price }}</td>
            <td>{{ item.description }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}